//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTSDCES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumRep
    {
        public int PostRepID { get; set; }
        public string Content { get; set; }
        public string Images { get; set; }
        public int PostID { get; set; }
        public int AccountID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ForumPost ForumPost { get; set; }
    }
}
