//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTSDCES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forum
    {
        public int PostID { get; set; }
        public Nullable<int> NumReps { get; set; }
        public string Title { get; set; }
        public Nullable<int> NumViews { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public int AccountID { get; set; }
        public string Description { get; set; }
        public string Images { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
